export const RENDER_ABOUT_SECTION = 'RENDER_ABOUT_SECTION';
export const RENDER_SKILLS_SECTION = 'RENDER_SKILLS_SECTION';
export const RENDER_PROJECTS_SECTION = 'RENDER_PROJECTS_SECTION';
export const RENDER_CONTACT_SECTION = 'RENDER_CONTACT_SECTION';
